# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'AzureGH'
    userRepository: 'jellyfin/jellyfin'
    defaultVersionType: 'latest'
    itemPattern: '*macos.tar.gz'
    downloadPath: '$(Build.SourcesDirectory)'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.gz'
    destinationFolder: '$(Build.SourcesDirectory)'
    cleanDestinationFolder: true

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'MacAnthony2.p12'
    certPwd: '$(CertificatePassword)'
    keychain: 'temp'
 
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'JellyfinMacProvision.provisionprofile'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'macosx10.15'
    xcWorkspacePath: '**/*.xcodeproj'
    packageApp: false
    signingOption: 'default'
    destinationPlatformOption: 'macOS'
    useXcpretty: false



- task: PublishBuildArtifacts@1
  displayName: 'Bundle Release'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build/Release/'
    ArtifactName: 'jellyfin-macos-wrapper.zip'
    publishLocation: 'Container'