# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'DevIDCert.p12'
    certPwd: '$(CertificatePassword)'
    keychain: 'temp'
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'macosx10.15'
    xcWorkspacePath: '**/*.xcodeproj'
    packageApp: false
    signingOption: 'auto'
    teamId: '6YC6EAV7ES'
    destinationPlatformOption: 'macOS'

- task: PublishBuildArtifacts@1
  displayName: 'Bundle Release'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build/Release/'
    ArtifactName: 'jellyfin-macos-wrapper.zip'
    publishLocation: 'Container'