# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'macosx10.15'
    xcWorkspacePath: '**/*.xcodeproj'
    packageApp: false
    signingOption: 'auto'
    teamId: '6YC6EAV7ES'
    destinationPlatformOption: 'macOS'